<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "auxlibs"
 *
 * Auto generated by Extension Builder 2018-05-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Auxillary libraries',
    'description' => 'Libraries from third parties',
    'category' => 'misc',
    'author' => 'Roman Büchler',
    'author_email' => 'rb@buechler.pro',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'Hashids\\' => 'Contrib/hashids.php/src'
        ],
    ],
];
